# Generated by Django 4.2 on 2023-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_academia', models.CharField(max_length=255)),
                ('Dono', models.CharField(max_length=255)),
                ('E_mail', models.EmailField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('Endereco', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
