# Generated by Django 4.2 on 2023-04-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_aluno_tipoavaliacao_alter_academia_dono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='telefone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='personal',
            name='telefone',
            field=models.IntegerField(default=None),
        ),
    ]
