# Generated by Django 4.2 on 2023-04-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_academia_telefone_aluno_telefone_personal_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academia',
            old_name='password',
            new_name='senha',
        ),
    ]
