# Generated by Django 4.2 on 2023-04-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_rename_password_academia_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='academia',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
