# Generated by Django 4.2 on 2023-05-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_aluno_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Valor_pagamento',
            field=models.CharField(max_length=10),
        ),
    ]
