# Generated by Django 4.2 on 2023-05-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_aluno_data_inscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 24, 52, 938251, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
