# Generated by Django 4.2 on 2023-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_aluno_academia_alter_avaliacao_academia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
