# Generated by Django 4.2 on 2023-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_academia_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
