# Generated by Django 4.2 on 2023-05-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_aluno_data_pagamento'),
        ('gym', '0014_alter_aluno_academia_alter_avaliacao_tipoavaliacao_and_more'),
    ]

    operations = [
    ]
