# Generated by Django 4.2 on 2023-05-31 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_merge_20230531_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 14, 56, 9, 999395, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
