# Generated by Django 4.2 on 2023-05-31 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_alter_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 6, 30, 15, 7, 46, 550054, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
