# Generated by Django 4.2 on 2023-06-16 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_alter_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 21, 28, 9, 24919, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
