# Generated by Django 4.2 on 2023-06-20 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_alter_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 20, 13, 10, 974294, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
