# Generated by Django 4.2 on 2023-06-20 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_alter_aluno_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Data_pagamento',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 20, 18, 49, 331471, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_abdomen',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_antebraco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_braco_contraido',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_braco_relaxado',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_cintura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_distal_coxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_medial_coxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_ombro',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_panturilha_coxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_pescoco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_prox_coxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_quadril',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Circoferencia_torax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Dobra_axilar_media',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Dobra_coxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Dobra_toracica',
            field=models.FloatField(null=True),
        ),
    ]
